version: "3.8"

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"   # truy cập web app tại localhost:8080
      - "9003:9003" # cổng debug cho Xdebug
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: QLCT
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - ./sources/qlct:/var/www/html
    networks:
      - qlct_network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: QLCT
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306" # tránh trùng với MySQL máy
    volumes:
      - ./data:/var/lib/mysql
      - ./sources/qlct/database/init-permissions.sql:/docker-entrypoint-initdb.d/init-permissions.sql
    networks:
      - qlct_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80" # truy cập phpMyAdmin tại localhost:8081
    networks:
      - qlct_network

networks:
  qlct_network:
    driver: bridge
